services:

  db:
    image: postgres:latest
    container_name: postgresql_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: YozhkinMaks
      POSTGRES_PASSWORD: Yozhkin24012003
      POSTGRES_DB: RepairLocDepot
    ports:
      - 5432:5432
    volumes:
      - ./datadb/:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  django:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./yozhkindjangoproject/:/usr/src/django
    ports:
      - 8000:8000
    depends_on:
      - db