# Generated by Django 5.1.3 on 2024-12-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigades',
            fields=[
                ('number_brigade', models.AutoField(primary_key=True, serialize=False)),
                ('number_phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'brigades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locomotives',
            fields=[
                ('reg_number', models.AutoField(primary_key=True, serialize=False)),
                ('reg_depo', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=30)),
                ('year_prod', models.DateField()),
            ],
            options={
                'db_table': 'locomotives',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repairs',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('date_start', models.DateField()),
                ('needed_days', models.IntegerField()),
                ('cost_one_day', models.TextField()),
            ],
            options={
                'db_table': 'repairs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('code_worker', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=20)),
                ('brigadier', models.BooleanField()),
                ('date_birth', models.DateField()),
            ],
            options={
                'db_table': 'workers',
                'managed': False,
            },
        ),
    ]
